[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pasta"
version = "0.1.1"
description = "PASTA - Gigapixel multilevel virtual tumor tissue phenotyping by pathological foundation models"
requires-python = ">=3.8"
authors = [
    {name = "Fangliangzi Meng", email = "mengflz@tongji.edu.cn"}
]

[tool.setuptools.packages.find]
where = ["."]
include = ["pasta*"]

